title: "HomeLab Blog"
description: "Documenting my cybersecurity homelab journey."
theme: minima

# Enable blog posts
collections:
  posts:
    output: true

# Hide duplicate title in footer
show_excerpts: false
header_pages: []
